import type { CompleteCVForPDF } from '../types/complete-cv';

export const sampleCVData: CompleteCVForPDF = {
  header: {
    full_name: 'Alexandra Chen',
    email: 'alexandra.chen@email.com',
    phone: '(555) 234-5678',
    location: 'San Francisco, CA',
    linkedin_url: 'linkedin.com/in/alexandrachen',
    github_url: 'github.com/alexchen',
    portfolio_url: 'alexchen.dev',
  },

  summary: 'Experienced software engineer with 8+ years of expertise in full-stack development, cloud architecture, and team leadership. Proven track record of delivering scalable applications and leading engineering teams. Strong background in JavaScript, Python, cloud technologies, and agile methodologies.',

  sections: {
    experience: [
      {
        id: 'exp1',
        title: 'Senior Software Engineer',
        organization: 'Tech Solutions Inc.',
        start_date: '2020-01-15',
        end_date: null,
        location: 'San Francisco, CA',
        link: null,
        bullets: [
          { id: 'exp1-b1', content: 'Led development of microservices architecture serving over 1 million daily active users', sort_order: 1 },
          { id: 'exp1-b2', content: 'Implemented CI/CD pipelines reducing deployment time by 60 percent', sort_order: 2 },
          { id: 'exp1-b3', content: 'Mentored team of 5 junior developers and conducted regular code reviews', sort_order: 3 },
          { id: 'exp1-b4', content: 'Optimized database queries improving API response time by 40 percent', sort_order: 4 },
        ],
        sort_order: 1,
      },
      {
        id: 'exp2',
        title: 'Software Engineer',
        organization: 'Digital Innovations LLC',
        start_date: '2018-06-01',
        end_date: '2019-12-31',
        location: 'Remote',
        link: null,
        bullets: [
          { id: 'exp2-b1', content: 'Developed full-stack web applications using React, Node.js, and PostgreSQL', sort_order: 1 },
          { id: 'exp2-b2', content: 'Built RESTful APIs and integrated third-party services', sort_order: 2 },
          { id: 'exp2-b3', content: 'Participated in agile development processes and sprint planning', sort_order: 3 },
        ],
        sort_order: 2,
      },
    ],

    projects: [
      {
        id: 'proj1',
        title: 'E-commerce Platform',
        organization: null,
        start_date: '2021-03-01',
        end_date: '2021-08-31',
        location: null,
        link: 'github.com/alexchen/ecommerce-platform',
        bullets: [
          { id: 'proj1-b1', content: 'Built scalable e-commerce platform with React and Node.js', sort_order: 1 },
          { id: 'proj1-b2', content: 'Implemented payment processing and order management system', sort_order: 2 },
        ],
        sort_order: 1,
      },
      {
        id: 'proj2',
        title: 'Real-time Chat Application',
        organization: null,
        start_date: '2020-09-01',
        end_date: '2020-12-31',
        location: null,
        link: 'github.com/alexchen/chat-app',
        bullets: [
          { id: 'proj2-b1', content: 'Developed real-time chat application using WebSockets and React', sort_order: 1 },
          { id: 'proj2-b2', content: 'Deployed on AWS with auto-scaling capabilities', sort_order: 2 },
        ],
        sort_order: 2,
      },
    ],

    education: [
      {
        id: 'edu1',
        title: 'Bachelor of Science in Computer Science',
        organization: 'University of California, Berkeley',
        start_date: '2012-09-01',
        end_date: '2016-05-31',
        location: 'Berkeley, CA',
        link: null,
        bullets: [
          { id: 'edu1-b1', content: 'GPA: 3.8 out of 4.0', sort_order: 1 },
          { id: 'edu1-b2', content: 'Relevant coursework: Data Structures, Algorithms, Database Systems', sort_order: 2 },
        ],
        sort_order: 1,
      },
    ],

    skills: [
      {
        id: 'skill1',
        title: 'Programming Languages',
        organization: null,
        start_date: null,
        end_date: null,
        location: null,
        link: null,
        bullets: [{ id: 'skill1-b1', content: 'JavaScript, TypeScript, Python, Java, Go', sort_order: 1 }],
        sort_order: 1,
      },
      {
        id: 'skill2',
        title: 'Frameworks & Libraries',
        organization: null,
        start_date: null,
        end_date: null,
        location: null,
        link: null,
        bullets: [{ id: 'skill2-b1', content: 'React, Next.js, Node.js, Express, Django, Flask', sort_order: 1 }],
        sort_order: 2,
      },
      {
        id: 'skill3',
        title: 'Cloud & DevOps',
        organization: null,
        start_date: null,
        end_date: null,
        location: null,
        link: null,
        bullets: [{ id: 'skill3-b1', content: 'AWS, Docker, Kubernetes, Jenkins, Git, CI/CD', sort_order: 1 }],
        sort_order: 3,
      },
    ],

    certifications: [
      {
        id: 'cert1',
        title: 'AWS Certified Solutions Architect - Associate',
        organization: 'Amazon Web Services',
        start_date: '2021-06-15',
        end_date: null,
        location: null,
        link: 'aws.amazon.com/verification',
        bullets: [{ id: 'cert1-b1', content: 'Credential ID: AWS-123456', sort_order: 1 }],
        sort_order: 1,
      },
      {
        id: 'cert2',
        title: 'Certified Scrum Master',
        organization: 'Scrum Alliance',
        start_date: '2020-03-10',
        end_date: null,
        location: null,
        link: null,
        bullets: [],
        sort_order: 2,
      },
    ],

    other: [
      {
        id: 'other1',
        title: 'Open Source Contributor',
        organization: 'Various Projects',
        start_date: '2019-01-01',
        end_date: null,
        location: null,
        link: 'github.com/alexchen',
        bullets: [
          { id: 'other1-b1', content: 'Contributed to 10+ open source projects', sort_order: 1 },
          { id: 'other1-b2', content: 'Maintained popular React component library', sort_order: 2 },
        ],
        sort_order: 1,
      },
    ],
  },

  metadata: {
    cv_title: 'Software Engineer Resume',
    target_job_title: 'Senior Software Engineer',
    target_company: 'Tech Solutions Inc.',
    generated_date: '2024-01-15T10:30:00Z',
  },
};

export const sampleCVShort: CompleteCVForPDF = {
  header: {
    full_name: 'Alexandra Chen',
    email: 'alexandra.chen@email.com',
    phone: '(555) 234-5678',
    location: 'San Francisco, CA',
    linkedin_url: 'linkedin.com/in/alexandrachen',
    github_url: 'github.com/alexchen',
    portfolio_url: null,
  },
  summary: 'Full-stack developer with experience in JavaScript, React, and Node.js.',
  sections: {
    experience: [
      {
        id: 's-exp1',
        title: 'Software Engineer',
        organization: 'StartupCo',
        start_date: '2022-01-01',
        end_date: null,
        location: 'Remote',
        link: null,
        bullets: [
          { id: 's-exp1-b1', content: 'Built and maintained React applications for internal tools', sort_order: 1 },
          { id: 's-exp1-b2', content: 'Collaborated with designers and product managers on feature delivery', sort_order: 2 },
        ],
        sort_order: 1,
      },
    ],
    projects: [],
    education: [
      {
        id: 's-edu1',
        title: 'BSc Computer Science',
        organization: 'State University',
        start_date: '2016-09-01',
        end_date: '2020-05-31',
        location: 'City, State',
        link: null,
        bullets: [{ id: 's-edu1-b1', content: 'GPA: 3.7 / 4.0', sort_order: 1 }],
        sort_order: 1,
      },
    ],
    skills: [
      {
        id: 's-skill1',
        title: 'Programming Languages',
        organization: null,
        start_date: null,
        end_date: null,
        location: null,
        link: null,
        bullets: [{ id: 's-skill1-b1', content: 'JavaScript, TypeScript', sort_order: 1 }],
        sort_order: 1,
      },
      {
        id: 's-skill2',
        title: 'Frameworks & Tools',
        organization: null,
        start_date: null,
        end_date: null,
        location: null,
        link: null,
        bullets: [{ id: 's-skill2-b1', content: 'React, Node.js, Git', sort_order: 1 }],
        sort_order: 2,
      },
    ],
    certifications: [],
    other: [],
  },
  metadata: {
    cv_title: 'Short Software Engineer Resume',
    target_job_title: 'Software Engineer',
    target_company: null,
    generated_date: '2024-01-15T10:30:00Z',
  },
};

export const sampleCVLong: CompleteCVForPDF = {
  ...sampleCVData,
  sections: {
    ...sampleCVData.sections,
    experience: [
      ...sampleCVData.sections.experience,
      {
        id: 'exp3',
        title: 'Lead Engineer',
        organization: 'Global Tech Corp',
        start_date: '2016-01-01',
        end_date: '2018-12-31',
        location: 'New York, NY',
        link: null,
        bullets: [
          { id: 'exp3-b1', content: 'Led cross-functional teams delivering enterprise software solutions', sort_order: 1 },
          { id: 'exp3-b2', content: 'Introduced CI/CD pipelines improving deployment frequency by 50 percent', sort_order: 2 },
          { id: 'exp3-b3', content: 'Defined technical roadmaps with product and executive stakeholders', sort_order: 3 },
        ],
        sort_order: 3,
      },
      {
        id: 'exp4',
        title: 'Software Engineer II',
        organization: 'Innovate Labs',
        start_date: '2013-01-01',
        end_date: '2015-12-31',
        location: 'Boston, MA',
        link: null,
        bullets: [
          { id: 'exp4-b1', content: 'Developed backend services in Node.js and Python', sort_order: 1 },
          { id: 'exp4-b2', content: 'Improved application performance and reliability through refactoring', sort_order: 2 },
        ],
        sort_order: 4,
      },
    ],
    projects: [
      ...sampleCVData.sections.projects,
      {
        id: 'proj3',
        title: 'Analytics Dashboard',
        organization: null,
        start_date: '2019-01-01',
        end_date: '2019-09-30',
        location: null,
        link: 'github.com/alexchen/analytics-dashboard',
        bullets: [
          { id: 'proj3-b1', content: 'Designed and implemented analytics dashboards for executive reporting', sort_order: 1 },
          { id: 'proj3-b2', content: 'Integrated multiple data sources into a unified analytics platform', sort_order: 2 },
        ],
        sort_order: 3,
      },
      {
        id: 'proj4',
        title: 'Internal Tools Suite',
        organization: null,
        start_date: '2018-01-01',
        end_date: '2018-12-31',
        location: null,
        link: null,
        bullets: [{ id: 'proj4-b1', content: 'Built internal tools to streamline QA and deployment workflows', sort_order: 1 }],
        sort_order: 4,
      },
    ],
    education: [
      ...sampleCVData.sections.education,
      {
        id: 'edu2',
        title: 'Master of Science in Computer Science',
        organization: 'Tech University',
        start_date: '2016-09-01',
        end_date: '2018-05-31',
        location: 'City, State',
        link: null,
        bullets: [{ id: 'edu2-b1', content: 'Thesis on scalable microservices architectures', sort_order: 1 }],
        sort_order: 2,
      },
    ],
    other: [
      ...sampleCVData.sections.other,
      {
        id: 'other2',
        title: 'Conference Speaker',
        organization: 'TechConf',
        start_date: '2020-01-01',
        end_date: '2023-01-01',
        location: null,
        link: null,
        bullets: [{ id: 'other2-b1', content: 'Presented talks on microservices, observability, and DevOps', sort_order: 1 }],
        sort_order: 2,
      },
      {
        id: 'other3',
        title: 'Mentor',
        organization: 'Developer Mentorship Program',
        start_date: '2019-01-01',
        end_date: null,
        location: null,
        link: null,
        bullets: [{ id: 'other3-b1', content: 'Mentored junior engineers on career growth and technical skills', sort_order: 1 }],
        sort_order: 3,
      },
    ],
  },
  metadata: {
    cv_title: 'Senior Software Engineer – Extended Experience',
    target_job_title: sampleCVData.metadata.target_job_title,
    target_company: sampleCVData.metadata.target_company,
    generated_date: sampleCVData.metadata.generated_date,
  },
};
